### ISSUE TITLE
Fix Python 2.7 builds for OSX and Windows

### ISSUE THREAD

**Issue by moorepants** [conda-forge/slycot-feedstock#17]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by moorepants** [comment]
It is not possible to build on Windows with flang for python 2.7 because flang only support vc14 and python 2.7 builds require vc9. See: https://github.com/conda-forge/openmp-feedstock/issues/21

**Comment by repagh** [comment]
It is past py27's bedtime. Can we close this?

**Comment by moorepants** [comment]
I think we should drop support for Python 2.7 when conda forge does. I'm not sure the status on it. I suspect that they'll have an autogenerated PR to all the repos to do that or something.

**Comment by moorepants** [comment]
Looks like conda forge has dropped these:

https://conda-forge.org/docs/user/announcements.html

Gonna close this, as it would be impossible to support Py 2.7 and Windows it seems.
