### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by moorepants** [conda-forge/slycot-feedstock#6]
Issue: Need to get this built for Windows but Fortran compiler is not available.

mumps builds on windows with fortran:

https://github.com/conda-forge/mumps-feedstock/blob/8753d5ac7b8b2dcd3685a9c06884336caa57d55f/recipe/meta.yaml

Maybe something similar can be used.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by repagh** [comment]
I finally managed with flang....

**Comment by moorepants** [comment]
fixed with #14
